/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/roulette_inner.glb -o src/components/Inner.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder003: THREE.Mesh
    Cylinder003_1: THREE.Mesh
    Cylinder003_2: THREE.Mesh
    center: THREE.Mesh
  }
  materials: {
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/roulette_inner.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.1, 0]} scale={[1, 0.1, 1]}>
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Material.006']} />
      </group>
      <mesh geometry={nodes.center.geometry} material={materials['Material.004']} position={[0, 0.1, 0]} scale={[1, 0.1, 1]} />
    </group>
  )
}

useGLTF.preload('/models/roulette_inner.glb')
