/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/roulette_outer.glb -o src/components/Outer.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder002: THREE.Mesh
    Cylinder002_1: THREE.Mesh
    Cylinder002_2: THREE.Mesh
  }
  materials: {
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/roulette_outer.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.1, 0]} scale={[1, 0.1, 1]}>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder002_2.geometry} material={materials['Material.008']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/roulette_outer.glb')
